import "./globals.css";

import classNames from "classnames";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";

const dmsans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
  fallback: ["Arial", "Helvetica", "sans-serif"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={classNames(
          dmsans.variable,
          "antialiased bg-slate-100 dark:bg-black min-h-screen"
        )}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
